### ISSUE TITLE
Error using fieldtype

### ISSUE THREAD

**Issue by rogertinch** [lukeyouell/craft-countryselect#1]
I'm on  Craft CMS 3.0.0-RC13 and tried using this field in an entry, but got what looks like a JSON decode error. [Here's the stack trace](https://gist.github.com/tinchalamo/6526289244274d0e1e4da75e3edb2cf3).

**Comment by lukeyouell** [comment]
Thanks! Not sure how I didn't spot that. Fixed in the next release.
