### ISSUE TITLE
How can I display the selected country? The entry field value is the two-letter country abbreviation.

### ISSUE THREAD

**Issue by andreimoment** [lukeyouell/craft-countryselect#7]
In my case, I've created a field called `country` based on the countryselect plugin.

The `{{entry.country}}` field returns the two-letter abbreviation. How can I access/return the full country name?

Thank you!

**Comment by Gnative** [comment]
If the field was called country then calling {{ entry.country.label }} will display the full country name.
There should really be some better documentation for this.

**Comment by andreimoment** [comment]
Thank you
